name: rx_text_field
description: "A reactive text field widget for Flutter that synchronizes with data models."
version: "0.1.1"
homepage: https://github.com/stevenosse/rx_text_field
repository: https://github.com/stevenosse/rx_text_field
issue_tracker: https://github.com/stevenosse/rx_text_field/issues

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
